packages:
- '.'
- location:
    git: https://github.com/lamdu/freetype2
    commit: b6b3f82b9f8acb925d8f36ecc1520832ad256444
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 839c7e00a7f48b33f13b7ce7914e713e4e2261ad
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: 585671664f9afb1dd306b0439007a0d5e9fe995a
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
resolver: lts-5.12
