packages:
- '.'
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 2151343a2a26031326d0ccfca65a69975b20b9f8
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: c2c42340985cc45c71b92d5294f775a0a16199d5
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
resolver: lts-7.14
